[package]
name = "rsgen-avro"
version = "0.7.0"
authors = ["Romain Leroux <romain@leroux.dev>"]
edition = "2018"
description = "Command line and library for generating Rust types from Avro schemas"
keywords = ["avro", "code-generation", "serde"]
repository = "https://github.com/lerouxrgd/rsgen-avro"
license = "MIT"
readme = "README.md"

[dependencies]
avro-rs = "0.11"
docopt = "1"
heck = "0.3"
lazy_static = "1.4"
# num-bigint = "0.2"
serde = { version = "1.0", features = ["serde_derive"] }
serde_json = "1.0"
tera = "1.5"
thiserror = "1.0"
uuid = { version = "0.8", features = ["serde", "v4"] }
