[package]
name = "rsgen-avro"
version = "0.8.1"
authors = ["Romain Leroux <romain@leroux.dev>"]
edition = "2018"
description = "Command line and library for generating Rust types from Avro schemas"
keywords = ["avro", "code-generation", "serde"]
repository = "https://github.com/lerouxrgd/rsgen-avro"
license = "MIT"
readme = "README.md"

[dependencies]
avro-rs = "0.12"
docopt = "1"
heck = "0.3"
lazy_static = "1"
serde = { version = "1", features = ["serde_derive"] }
serde_json = "1"
tera = "1"
thiserror = "1"
uuid = { version = "0.8", features = ["serde", "v4"] }
